# -*- coding: utf-8 -*-
"""Data Visualization Using Matplotlib.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ESBccGaP6QxnZ4vx50z-LcYygMeIYRu3
"""

import pandas as pd
import numpy as np
import matplotlib

# 1. Convert text file to csv

read_file = pd.read_csv(r'/content/dataset.txt', delimiter=' ')
read_file.to_csv(r'/content/dataset.csv', index=None)

covid_dataset = pd.read_csv(r'/content/dataset.csv')

row_num = covid_dataset.shape[0]
col_num = covid_dataset.shape[1]

print('row_num = ', row_num)
print('col_num = ', col_num)

covid_dataset.head(325437)